services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    env_file:
      - .env
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq

  redis:
    image: redis:7
    restart: on-failure
    ports:
      - "0.0.0.0:6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1